spring:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

server:
  servlet:
    session:
      cookie:
        same-site: lax
        secure: false

front:
  url: ${FRONT_URL}

aws:
  s3:
    endpointUrl: ${S3_ENDPOINT}
    region: ${S3_REGION}
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_KEY}
    bucketName: ${S3_BUCKET_NAME}
    publicUrl: ${S3_PUBLIC_URL}