spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}

server:
  servlet:
    session:
      cookie:
        same-site: lax
        secure: false

front:
  url: ${FRONT_URL}

aws:
  s3:
    endpointUrl: ${S3_ENDPOINT}
    region: ${S3_REGION}
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_KEY}
    bucketName: ${S3_BUCKET_NAME}
    publicUrl: ${S3_PUBLIC_URL}