name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: aster20/barrier-free-map
          stage: main
          yaml: |
            name: barrier-free-map-server
            app: java@21
            options:
              ports: "8080"
              env:
                - name: JAVA_OPTS
                  value: >-
                    -Xms64m -Xmx128m -XX:MaxMetaspaceSize=64m -XX:+UseSerialGC -XX:+AlwaysPreTouch -XX:+ExitOnOutOfMemoryError
                - name: S3_ENDPOINT
                  secret: S3_ENDPOINT
                - name: S3_REGION
                  secret: S3_REGION
                - name: S3_ACCESS_KEY
                  secret: S3_ACCESS_KEY
                - name: S3_SECRET_KEY
                  secret: S3_SECRET_KEY
                - name: S3_BUCKET_NAME
                  secret: S3_BUCKET_NAME
                - name: S3_PUBLIC_URL
                  secret: S3_PUBLIC_URL
                - name: FRONT_URL
                  secret: FRONT_URL
                - name: DB_URL
                  secret: DB_URL
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
